// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JOB_PORTAL.Models;

public partial class AcademicDetail
{
    public int AcademicId { get; set; }

    public int? JobSeekerId { get; set; }

    public string Class { get; set; }

    public DateOnly? StartYear { get; set; }

    public string CollegeUniversityName { get; set; }

    public DateOnly? EndYear { get; set; }

    public decimal? Cgpa { get; set; }

    public virtual JobSeeker JobSeeker { get; set; }
}