// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JOB_PORTAL.Models;

public partial class Branch
{
    public int BranchId { get; set; }

    public int? CompanyId { get; set; }

    public string BranchName { get; set; }

    public string Location { get; set; }

    public byte[] Password { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<EmployerDetail> EmployerDetails { get; set; } = new List<EmployerDetail>();
}