// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JOB_PORTAL.Models;

public partial class Company
{
    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public byte[] Password { get; set; }

    public string EmailId { get; set; }

    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();
}