// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JOB_PORTAL.Models;

public partial class EmployerDetail
{
    public int EmployerId { get; set; }

    public int? UserId { get; set; }

    public int? BranchId { get; set; }

    public string EmpName { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual Branch Branch { get; set; }

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();

    public virtual User User { get; set; }
}