// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JOB_PORTAL.Models;

public partial class Job
{
    public int JobId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateOnly? PostingDate { get; set; }

    public DateOnly? LastDate { get; set; }

    public string Location { get; set; }

    public string JobType { get; set; }

    public int? SkillId { get; set; }

    public string Domain { get; set; }

    public decimal? Salary { get; set; }

    public string ExperienceLevel { get; set; }

    public int? EmployerId { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual EmployerDetail Employer { get; set; }

    public virtual ICollection<Skill> Skills { get; set; } = new List<Skill>();
}