// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JOB_PORTAL.Models;

public partial class JobSeeker
{
    public int JobSeekerId { get; set; }

    public int? UserId { get; set; }

    public int? AcademicId { get; set; }

    public int? SkillId { get; set; }

    public int? ProfessionalId { get; set; }

    public string Address { get; set; }

    public string ExperienceLevel { get; set; }

    public DateOnly? Dob { get; set; }

    public byte[] Resume { get; set; }

    public virtual ICollection<AcademicDetail> AcademicDetails { get; set; } = new List<AcademicDetail>();

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual ICollection<ProfessionalDetail> ProfessionalDetails { get; set; } = new List<ProfessionalDetail>();

    public virtual ICollection<Skill> Skills { get; set; } = new List<Skill>();

    public virtual User User { get; set; }
}