// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JOB_PORTAL.Models;

public partial class ProfessionalDetail
{
    public int ProfessionalId { get; set; }

    public int? JobSeekerId { get; set; }

    public string CompanyName { get; set; }

    public string Designation { get; set; }

    public DateOnly? FromDate { get; set; }

    public DateOnly? ToDate { get; set; }

    public virtual JobSeeker JobSeeker { get; set; }
}