// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JOB_PORTAL.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public byte[] Password { get; set; }

    public string EmailId { get; set; }

    public string UserType { get; set; }

    public byte[] UserProfile { get; set; }

    public virtual ICollection<EmployerDetail> EmployerDetails { get; set; } = new List<EmployerDetail>();

    public virtual ICollection<JobSeeker> JobSeekers { get; set; } = new List<JobSeeker>();
}